### ISSUE TITLE
Vagrant fails to build nokogiri native extensions on Debian sid with ruby-2.6.6 vagrant 2.2.10 

### ISSUE THREAD

**Issue by kfrz** [hashicorp/vagrant-installers#175]
**System Configuration**

I'm using the following software versions:

```
virsh -v 6.6.0
Vagrant v 2.2.10
Linux 5.8.0-3-amd64
Debian GNU/Linux bullseye/sid
```
I've installed dependencies as such:

```sh
sudo apt build-dep vagrant ruby-libvirt
sudo apt install qemu libvirt-daemon-system libvirt-clients ebtables dnsmasq-base
sudo apt install libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
```

```
dnsmasq-base is already the newest version (2.82-1).
ebtables is already the newest version (2.0.11-4+b1).
libvirt-clients is already the newest version (6.6.0-2).
libvirt-daemon-system is already the newest version (6.6.0-2).
qemu is already the newest version (1:5.1+dfsg-4).
libvirt-dev is already the newest version (6.6.0-2).
libxml2-dev is already the newest version (2.9.10+dfsg-6.1).
libxslt1-dev is already the newest version (1.1.34-4).
ruby-dev is already the newest version (1:2.7+1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2).
```

**Problem** 

Installing `vagrant-libvirt` plugin on Debian 11 Bullseye, following instructions [here](https://github.com/vagrant-libvirt/vagrant-libvirt#installation) fails to build the Nokogiri gem native extensions. 

<details><summary>Truncated output of `vagrant plugin install vagrant-libvirt --debug`:</summary>

```log
DEBUG bundler: Removing activation request from install. Already installed. (webrick-1.4.2)
DEBUG bundler: Removing activation request from install. Already installed. (zlib-1.0.0)
DEBUG bundler: Installing required gems.
ERROR warden: Error occurred: Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /home/kf/.vagrant.d/gems/2.6.2/gems/nokogiri-1.10.10/ext/nokogiri
/tmp/.mount_vagranpTif9t/usr/bin/ruby2.6 -I /tmp/.mount_vagranpTif9t/usr/lib/ruby/2.6.0 -r ./siteconf20201022-385072-1bcghbz.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/tmp/.mount_vagranpTif9t/usr/bin/$(RUBY_BASE_NAME)2.6
	--help
	--clean
/tmp/.mount_vagranpTif9t/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /tmp/.mount_vagranpTif9t/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
	from /tmp/.mount_vagranpTif9t/usr/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror'
	from /tmp/.mount_vagranpTif9t/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /tmp/.mount_vagranpTif9t/usr/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/kf/.vagrant.d/gems/2.6.2/extensions/x86_64-linux/2.6.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1
```
</details>

<details><summary>Output of `../*/nokogiri-1.10.10/mkmf.log`:</summary>

```log
"gcc -o conftest -I/tmp/.mount_vagranpTif9t/usr/include/x86_64-linux-gnu/ruby-2.6.0 -I/tmp/.mount_vagranpTif9t/usr/include/ruby-2.6.0/ruby/backward -I/tmp/.mount_vagranpTif9t/usr/include/ruby-2.6.0 -I. -D_FORTIFY_SOURCE=2   -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC  conftest.c  -L. -L/tmp/.mount_vagranpTif9t/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.6  -lm   -lc "
In file included from /tmp/.mount_vagranpTif9t/usr/include/ruby-2.6.0/ruby/ruby.h:29,
                 from /tmp/.mount_vagranpTif9t/usr/include/ruby-2.6.0/ruby.h:33,
                 from conftest.c:1:
/tmp/.mount_vagranpTif9t/usr/include/ruby-2.6.0/ruby/defines.h:123:10: fatal error: stdio.h: No such file or directory
  123 | #include <stdio.h>
      |          ^~~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

</details>

After verifying all dependencies were installed, and after a reboot, the issue persists. 

`stdio.h` can be found on my local system:

```sh
$ find /usr/include/ -name "stdio.h"
/usr/include/x86_64-linux-gnu/bits/stdio.h
/usr/include/c++/10/tr1/stdio.h
/usr/include/stdio.h
``` 
---

I'm opening an issue here, after searching and reading through similar issues on MacOS (#163), though I do not have XCode available to solve in the same manner.

Building/installing `nokogiri-1.10.10` on `ruby 2.6.6` works on the local machine as well with `gem install nokogiri`

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. There have been multiple Vagrant releases since the original report, we recommend upgrading. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem.

Cheers!
